### ISSUE TITLE
"Three Columns" Plugin: Columns Are Too Narrow and Do Not Flow Properly Through the Page

### ISSUE THREAD

**Issue by franceslui** [ubc-web-services/ubc_ckeditor_widgets#17]
### Problem/Motivation
The columns generated by the "Three Columns" plugin are too narrow and do not flow through the page correctly.

### Steps to reproduce
1. Configure a text format such as "Basic HTML".
2. Drag the "Three Columns" plugin from the "Available buttons" section to the "Active toolbar" section.
3. Save the text format configuration page.
4. Create a new page.
5. Use the "Three Columns" plugin on the toolbar of the body to create 3 columns.
6. Add a substantial amount of text to each of the three generated columns.
7. Save the new page.

### Observed Behavior
The columns in both the text editor and the saved page are very narrow and do not flow through the page properly.

**Screenshots**

- Text Editor <img width="974" alt="Screenshot 2024-05-28 at 2 00 34 PM" src="https://github.com/ubc-web-services/ubc_ckeditor_widgets/assets/104601439/2b003444-b9ad-4241-b72f-81deff0bdd18">
- Saved Page 
   <img width="280" alt="Screenshot 2024-05-28 at 1 42 49 PM" src="https://github.com/ubc-web-services/ubc_ckeditor_widgets/assets/104601439/e6605b78-d4bc-4ca8-aafc-0f478db546ec">

**Notes**
When the "Three Vertical Cards" plugin is also moved from the "Available buttons" section to the "Active toolbar" section in the same text format configuration page, the "Three Columns" plugin generates columns that are not narrow and flow through the page correctly.

**Screenshots with "Three Vertical Cards" Plugin Enabled**

- Text Editor <img width="974" alt="Screenshot 2024-05-28 at 2 16 45 PM" src="https://github.com/ubc-web-services/ubc_ckeditor_widgets/assets/104601439/32953a71-e7ba-4c21-b787-6683de3e73d6">
- Saved Page
   <img width="915" alt="Screenshot 2024-05-28 at 2 18 12 PM" src="https://github.com/ubc-web-services/ubc_ckeditor_widgets/assets/104601439/984cce4f-cbdb-45f4-91fe-e2cd1b44ef55">

**Comment by joelpittet** [comment]
As a side note, the reason the editor looks incorrect is that a class doesn't get applied. I believe it was missing `widget-column-options` this is needed for the CSS and JS to function... strange is it kicks in when the other button is added

**Comment by occupant** [comment]
Thanks @joelpittet @franceslui , this really helped narrow it down. The model > view conversion for classes was mistakenly omitted from the columns widgets but WAS included with the 3 column widgets - that's why it worked when that widget was enabled vs with it disabled.

I've added the conversion to all of the appropriate widgets and this should correct the issue. The latest release 3.1.20 corrects the issue.
